name: Update Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '18 3 * * *'

jobs:
  update-packages:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31

      - name: Run update task
        env:
          SYSTEM: x86_64-linux
        run: nix run .#tasks.${SYSTEM}.update

      - uses: DeterminateSystems/update-flake-lock@c5930b397a673a70ca70be06020e943aeac310a1 # v27
        with:
          pr-title: "chore(deps): update packages"
          pr-labels: |
            dependencies
            automated
